language: go

go:
  - 1.8
  - tip

go_import_path: gopkg.in/bblfsh/sdk.v1

matrix:
  fast_finish: true
  allow_failures:
    - go: tip


before_install:
  - make validate-commit
  - go get -t -v ./...

script:
  - make test-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
