language: go

go:
  - '1.11.x'
  - '1.12.x'
  - tip

go_import_path: gopkg.in/bblfsh/sdk.v2

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

before_install:
  - cd $GOPATH/src/gopkg.in/bblfsh/sdk.v2
  - make validate-commit
  - go mod download

script:
  - make test-coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
